// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Milefer7/compliation_exp/dal/model"
)

func newKeywords(db *gorm.DB, opts ...gen.DOOption) keywords {
	_keywords := keywords{}

	_keywords.keywordsDo.UseDB(db, opts...)
	_keywords.keywordsDo.UseModel(&model.Keywords{})

	tableName := _keywords.keywordsDo.TableName()
	_keywords.ALL = field.NewAsterisk(tableName)
	_keywords.Id = field.NewInt(tableName, "id")
	_keywords.Keyword = field.NewString(tableName, "keyword")

	_keywords.fillFieldMap()

	return _keywords
}

type keywords struct {
	keywordsDo

	ALL     field.Asterisk
	Id      field.Int
	Keyword field.String

	fieldMap map[string]field.Expr
}

func (k keywords) Table(newTableName string) *keywords {
	k.keywordsDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k keywords) As(alias string) *keywords {
	k.keywordsDo.DO = *(k.keywordsDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *keywords) updateTableName(table string) *keywords {
	k.ALL = field.NewAsterisk(table)
	k.Id = field.NewInt(table, "id")
	k.Keyword = field.NewString(table, "keyword")

	k.fillFieldMap()

	return k
}

func (k *keywords) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *keywords) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 2)
	k.fieldMap["id"] = k.Id
	k.fieldMap["keyword"] = k.Keyword
}

func (k keywords) clone(db *gorm.DB) keywords {
	k.keywordsDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k keywords) replaceDB(db *gorm.DB) keywords {
	k.keywordsDo.ReplaceDB(db)
	return k
}

type keywordsDo struct{ gen.DO }

func (k keywordsDo) Debug() *keywordsDo {
	return k.withDO(k.DO.Debug())
}

func (k keywordsDo) WithContext(ctx context.Context) *keywordsDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k keywordsDo) ReadDB() *keywordsDo {
	return k.Clauses(dbresolver.Read)
}

func (k keywordsDo) WriteDB() *keywordsDo {
	return k.Clauses(dbresolver.Write)
}

func (k keywordsDo) Session(config *gorm.Session) *keywordsDo {
	return k.withDO(k.DO.Session(config))
}

func (k keywordsDo) Clauses(conds ...clause.Expression) *keywordsDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k keywordsDo) Returning(value interface{}, columns ...string) *keywordsDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k keywordsDo) Not(conds ...gen.Condition) *keywordsDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k keywordsDo) Or(conds ...gen.Condition) *keywordsDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k keywordsDo) Select(conds ...field.Expr) *keywordsDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k keywordsDo) Where(conds ...gen.Condition) *keywordsDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k keywordsDo) Order(conds ...field.Expr) *keywordsDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k keywordsDo) Distinct(cols ...field.Expr) *keywordsDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k keywordsDo) Omit(cols ...field.Expr) *keywordsDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k keywordsDo) Join(table schema.Tabler, on ...field.Expr) *keywordsDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k keywordsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *keywordsDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k keywordsDo) RightJoin(table schema.Tabler, on ...field.Expr) *keywordsDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k keywordsDo) Group(cols ...field.Expr) *keywordsDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k keywordsDo) Having(conds ...gen.Condition) *keywordsDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k keywordsDo) Limit(limit int) *keywordsDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k keywordsDo) Offset(offset int) *keywordsDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k keywordsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *keywordsDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k keywordsDo) Unscoped() *keywordsDo {
	return k.withDO(k.DO.Unscoped())
}

func (k keywordsDo) Create(values ...*model.Keywords) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k keywordsDo) CreateInBatches(values []*model.Keywords, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k keywordsDo) Save(values ...*model.Keywords) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k keywordsDo) First() (*model.Keywords, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Keywords), nil
	}
}

func (k keywordsDo) Take() (*model.Keywords, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Keywords), nil
	}
}

func (k keywordsDo) Last() (*model.Keywords, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Keywords), nil
	}
}

func (k keywordsDo) Find() ([]*model.Keywords, error) {
	result, err := k.DO.Find()
	return result.([]*model.Keywords), err
}

func (k keywordsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Keywords, err error) {
	buf := make([]*model.Keywords, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k keywordsDo) FindInBatches(result *[]*model.Keywords, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k keywordsDo) Attrs(attrs ...field.AssignExpr) *keywordsDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k keywordsDo) Assign(attrs ...field.AssignExpr) *keywordsDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k keywordsDo) Joins(fields ...field.RelationField) *keywordsDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k keywordsDo) Preload(fields ...field.RelationField) *keywordsDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k keywordsDo) FirstOrInit() (*model.Keywords, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Keywords), nil
	}
}

func (k keywordsDo) FirstOrCreate() (*model.Keywords, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Keywords), nil
	}
}

func (k keywordsDo) FindByPage(offset int, limit int) (result []*model.Keywords, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k keywordsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k keywordsDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k keywordsDo) Delete(models ...*model.Keywords) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *keywordsDo) withDO(do gen.Dao) *keywordsDo {
	k.DO = *do.(*gen.DO)
	return k
}
